#!/usr/bin/env bash
# Install load balancer HAproxy with version 1.5 or greater
apt-get -y update
apt-get install haproxy -y

echo "ENABLED=1" >> /etc/default/haproxy

echo -e "\nlisten 1540-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\toption forwardfor\n\tserver 1540-web-01	34.74.27.162:80 check\n\tserver 1540-web-02 54.224.88.154:80 check\n" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
