#!/usr/bin/env bash
# prints Holberton School ten times but prints hi after 9th iteration
i=1
while [ $i -le 10 ]; do # -lt stands for less than or equal to
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    let i+=1;
done