#!/usr/bin/env bash
# prints a certain phrase if conditions are met
i=1
while [ $i -le 10 ]; do # -le stands for less than or equal to
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let i+=1;
done