#!/usr/bin/env bash
# This script prints the time in seconds for 12 hours
hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    min=1
    while [ $min -le 59 ]
    do
        echo $min
        let min+=1
    done
    let hour+=1
done
