#!/usr/bin/env bash
# displays information about a file
fd="holbertonschool"
if [ -e $fd ] # -e stands for exists
then
    echo "holbertonschool file exists"
    if [ -s $fd ] # -s whether file is empty or not
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if [ -f $fd ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
